### ISSUE TITLE
Multiple overlay styles in same app

### ISSUE THREAD

**Issue by nicgirault** [AlexanderRichey/styled-react-modal#14]
Thanks for this lightweight library.

I have 2 kind of modals in my app with different overlays but overlay is specified in Provider. Is there a way to specify different overlays?

Maybe the provider overlay could be overriden by an overlay prop of the modal?

**Comment by AlexanderRichey** [comment]
I think you could use the `backgroundProps` prop to achieve this. You can see this in action in the [demo](https://codesandbox.io/s/m9jlky57y), where it is used to create the fade animation. You could use it to change the color of the overlay or whatever prop you like. You would just have to make sure that the `<Background />` that you write accepts the relevant props.
