### ISSUE TITLE
Overlay transparency

### ISSUE THREAD

**Issue by lishine** [AlexanderRichey/styled-react-modal#2]
Hi,
How do I set overlay transparency?
Thanks

**Comment by lishine** [comment]
And I use this, and it shows nothing...
```
import Modal, { ModalProvider } from 'styled-react-modal'
import styled from 'styled-components'

const StyledModal = Modal.styled`
  width: 25rem;
  height: 30rem;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: blue;
  opacity: ${(props) => props.opacity};
  transition: opacity ease 200ms;
`

export default () => (
	<div>
		<ModalProvider>
			<StyledModal isOpen opacity={0.2}>
				<span>I am a modal!</span>
			</StyledModal>
		</ModalProvider>
	</div>
)
```

**Comment by AlexanderRichey** [comment]
You should be able to by setting the opacity in the styles. For example,
```
const StyledModal = Modal.styled`
  opacity: 0.5;
  ...
`
```
I [forked the demo on CodeSandbox](https://codesandbox.io/s/3r2lv1kjq6) and changed the `opacity` property to demonstrate. Let me know if this helps!

**Comment by lishine** [comment]
It changes opacity of the modal
I mean to change the opacity of the window behind the modal

**Comment by AlexanderRichey** [comment]
All you have to do is pass in a `backgroundComponent` to the `<ModalProvider />`. For example:

```
import { ModalProvider } from 'styled-react-modal'

const ModalBackground = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  z-index: 30;
  background-color: green;
  opacity: 0.5;
`

export default class App extends Component {
  render () {
    return (
      <div>
        <ModalProvider backgroundComponent={ModalBackground}>
          <YourApp />
        </ModalProvider>
      </div>
    )
  }
}
```

If you want to animate the background, or if you want different backgrounds for different `<Modal />` instances, then I recommend making a transparent `<ModalBackground />` component to pass into the `<ModalProvider />`. You could then make different `<Background />` components to use in your `<Modal />` instances.

Let me know if this clears things up!
