### ISSUE TITLE
How to contribute!?

### ISSUE THREAD

**Issue by xMokAx** [AlexanderRichey/styled-react-modal#20]
I cloned the repo and added some features. How should I test those features in a real react app?. After making sure that my app works as expected, should I just submit a pull request?.

**Comment by AlexanderRichey** [comment]
You can test your changes locally using [`npm link` or `yarn link`](https://yarnpkg.com/lang/en/docs/cli/link/). I have a big refactor in the dev branch we're I've rewritten the library using hooks. So any new features you may want to add should target that branch. Thanks!

**Comment by xMokAx** [comment]
The develop branch looks promising. `prettier`, eslint config and plugins and styled-components are added to devDependencies which is great. Hooks are used. Great work.
