### ISSUE TITLE
Trap focus within modal

### ISSUE THREAD

**Issue by davidcsally** [AlexanderRichey/styled-react-modal#23]
Hi @AlexanderRichey, have you thought about trapping focus in the modal when it's open for better accessibility?

**Comment by AlexanderRichey** [comment]
I have thought about this feature and would like to add it. I'm just not sure when I'll have the time to do so -- I have a lot going on at work and with other projects that is preventing me from working on this at the moment. I'm open to PRs, however. One strategy for achieving most of the [WAI-ARIA spec](https://www.w3.org/TR/wai-aria-practices/#dialog_modal) is wrap the modal content in a `<FocusTrap />` component and to add a few attributes by default. I'd be happy to merge a PR that does this in a simple way.

**Comment by AlexanderRichey** [comment]
In the [latest release](https://github.com/AlexanderRichey/styled-react-modal/releases/tag/v3.0.0), I added a [link to a CodeSandbox](https://codesandbox.io/s/styled-react-modal-a11y-9uco3?file=/src/index.js) that shows how to make an accessible modal with styled-react-modal, which I hope addresses your concern here.
