### ISSUE TITLE
Should isOpen be false by default?

### ISSUE THREAD

**Issue by zhulduz** [AlexanderRichey/styled-react-modal#3]
Maybe `state.isOpen` should set initial value from props?

**Comment by AlexanderRichey** [comment]
Yeah, it probably should. I'll add this in the next release, which will hopefully be this weekend or next.

**Comment by AlexanderRichey** [comment]
Fixed in [v1.1.1](https://github.com/AlexanderRichey/styled-react-modal/releases/tag/v1.1.1)
