### ISSUE TITLE
Add animation

### ISSUE THREAD

**Issue by maximeBreham** [AlexanderRichey/styled-react-modal#34]
Hi, how i can add some animations, to make the opening less brutal.
I try a transition : all 0.3s ease-in-out; 
But nothing change.

**Comment by AlexanderRichey** [comment]
You'll have to change the styles using the `afterOpen()` and `beforeClose()` props. If you want to make the background fade as well, you'll have to provide a custom background component. Here's a sandbox that shows how it's done: https://codesandbox.io/s/styled-react-modal-better-fading-pbokz?file=/src/index.js
