### ISSUE TITLE
ModalProvider Issue

### ISSUE THREAD

**Issue by ibrahimyaacob92** [AlexanderRichey/styled-react-modal#58]
![image](https://user-images.githubusercontent.com/58116068/167232820-6fc2af90-3af5-4fd6-9c61-2c26ed6b68a0.png)

**Comment by sohammondal** [comment]
I was having the same issue with Next.js v11.1.3. Downgrading to `v2.1.0` seems to have solved the issue for me.

**Comment by AlexanderRichey** [comment]
Dup of #54 and #57. See the threads of those issues. Also see the README:

> For support for create-react-app <5.0.0, please import from styled-react-modal/build/umd.
