### ISSUE TITLE
Modal gets closed when mousedown in the body and mouseup in the background

### ISSUE THREAD

**Issue by elco45** [AlexanderRichey/styled-react-modal#59]
When using the onBackgroundClick prop to manage the closing of the modal, I'm seeing that it closes the modal when we click-hold inside the body of the modal and then releasing the mouse click in the background.

The correct behaviour should be closing the modal only if you clicking with/without release in the background.

**Comment by AlexanderRichey** [comment]
This is a dupe. I think this comment might help you fix the issue you're facing: https://github.com/AlexanderRichey/styled-react-modal/issues/45#issuecomment-987619225
