### ISSUE TITLE
Is it possible to use tailwind utility classes instead of css ?

### ISSUE THREAD

**Issue by hackwithharsha** [AlexanderRichey/styled-react-modal#65]
In the following example, we are using CSS.. is it possible to replace them with tailwind utility classes? If so, how to do it ?

```js
const StyledModal = Modal.styled`
  width: 20rem;
  height: 20rem;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: ${props => props.theme.colors.white};
`
```

**Comment by AlexanderRichey** [comment]
You can use the `className` prop on the resulting component. Or just put a child component under the `<Modal />` component and put your tailwind classes there. For example:

```jsx
<Modal isOpen={isOpen} />
  <div className="pt-6 space-y-4" />
</Modal>
```
