### ISSUE TITLE
Updating styled-components version to ^6.x.x

### ISSUE THREAD

**Issue by HussainAbdi** [AlexanderRichey/styled-react-modal#69]
I would like to make a PR to update the styled-components version to work with existing projects that currently use styled-components 6.x.x and above. Currently, the dev dependencies use version ^5.x.x which means they will cause conflict issues when installing on a project that uses 6.x.x versions. Are there any checks in place to make sure that this project will work when this update is done?

**Comment by AlexanderRichey** [comment]
Hi, thank you, that would be great. 🙂 Yes, there are some checks. There are tests and there's also an integration with codesandbox that runs the modal in a little example React app to make sure it works.

**Comment by AlexanderRichey** [comment]
Merged your PR and published on NPM. Thank you @HussainAbdi! 🙂

**Comment by HussainAbdi** [comment]
Glad to be of some help! Thank you for your quick action @AlexanderRichey, I needed this for my [project](https://github.com/HussainAbdi/TuneTrove) 🙂
