### ISSUE TITLE
Incorrect syntax used in the Using example

### ISSUE THREAD

**Issue by ComradeLV** [AlexanderRichey/styled-react-modal#74]
In the second code block of [Usage](https://github.com/AlexanderRichey/styled-react-modal?tab=readme-ov-file#usage) chapter in README and in package description in NPM there is a following code:

```
...

function FancyModalButton() {
  const [isOpen, setIsOpen] = useState(false)

  function toggleModal(e) {
    setIsOpen(!isOpen)
  }

  render () {
    return (
      <div>
        <button onClick={toggleModal}>Click me</button>
        <StyledModal
          isOpen={isOpen}
          onBackgroundClick={toggleModal}
          onEscapeKeydown={toggleModal}>
          <span>I am a modal!</span>
          <button onClick={toggleModal}>Close me</button>
        </StyledModal>
      </div>
    )
  }
}
```

Mentioning `render` there is wrong since it is a member of Class Components and in Functional components we only use do `return`

**Comment by AlexanderRichey** [comment]
You're right. I must have made a mistake when updating the docs for hooks years ago. Would you mind submitting a PR to fix this?

**Comment by ComradeLV** [comment]
Sure, there is a [pull request](https://github.com/AlexanderRichey/styled-react-modal/pull/75)

**Comment by AlexanderRichey** [comment]
Thank you, @ComradeLV! 👍
